### ISSUE TITLE
Add details in the Contributing.md file (Hacktober Fest)

### ISSUE THREAD

**Issue by abrehan2** [antzshrek/hacktoberfest_2019#14]
Hi,

I will add my details in the CONTRIBUTING.md file.

Best,
Rehan

**Comment by antzshrek** [comment]
sure @abrehan2 feel free to do so as long as you update a file or create a valid file in your choice language.
Happy HacktOberfest

**Comment by vr1Ravi** [comment]
@antzshrek  could you please review the changes

**Comment by jodoesgit** [comment]
This issue can be closed.
